### ISSUE TITLE
save scores to scoreboard/localStorage across multiple game sessions

### ISSUE THREAD

**Issue by lingtran** [s-espinosa/qbert#36]

**Comment by s-espinosa** [comment]
At the end of a game, when the "Play Again" button appears

A user sees their score,
has the opportunity to enter their initials,
clicks save,
and their score is added to high scores that are saved locally.
The user then sees a list of the top five highest scores.

The user can click play again at any point.

As long as a user does not clear their cookies, they should be able to close their browser, open their browser, play a game, and see the same high scores.

**Comment by lingtran** [comment]
Created: 
- Scoreboard class with localStorage
- placeholders for score-form and top-scores in index.html

To do: 
- instantiate scoreboard
- capture this.score.total and player via Scoreboard.addGame -- should work...
- then Scoreboard.display in the end-menu
- add event listener so that on click of  'record score' button, transition to show #top-scores

**Comment by s-espinosa** [comment]
When the game ends
The game over screen is displayed
It has a final score for the user
a place to enter your initials
and a button to submit your score for top scores,
and the existing top five scores
You also see a button that allows you to restart.

When you enter your initials and hit submit
The top five scores are updated
and the restart button is still there.

**Comment by lingtran** [comment]
testing
